version: "3.9"
services:
  frontend:
    build:
      context: ./DevClient
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./DevMeet
    ports:
      - "3000:3000"
    env_file:
      - ./DevMeet/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
